### ISSUE TITLE
RC3 fails hello-param.cwl

### ISSUE THREAD

**Issue by buchanae** [rabix/bunny#165]
I think this is caused by an unhandled newline passed directly to the echo command.

https://github.com/common-workflow-language/workflows/blob/master/workflows/hello/hello-param.cwl

```
java -jar rabix-backend-local/target/rabix-backend-local-1.0.0-rc3.jar cwl-workflows/workflows/hello/hello-param.cwl#main cwl-workflows/workflows/hello/params.json

...

09:37:30.461 [JobHandler-Thread-0] INFO  verbose - Running command line: echo -n -e Hello, CWL !
Hello World ! > /Users/buchanae/projects/bunny/cwl-workflows/workflows/hello/hello-param-20170223093729429/root/step0/useroutput.txt
...

09:37:32.064 [Thread-1] INFO  verbose - Failed to execute a Job
...

cat workflows/hello/hello-param-20170223093729429/root/step0/job.err.log
/bin/bash: line 1: Hello: command not found
```

**Comment by StarvingMarvin** [comment]
Yeah, when I was playing with this tool yesterday, I haven't tried it with provided inputs file, so I didn't notice. Working on it.

**Comment by buchanae** [comment]
@StarvingMarvin Thanks!

I think I ran into the same issue while running the conformance tests. I'll describe here so we can decide if it's the same fix. I was running the TES backend when I hit this issue.

Running:
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/env-tool1.cwl
```
baseCommand: ["/bin/bash", "-c", "echo $TEST_ENV"]
```

gets written to `command.sh` as:
```
/bin/sh -c echo $TEST_ENV
```

but this isn't a well formed `sh -c` command. We'd need quotes around the `echo $TEST_ENV` part I think. I guess the CWL spec expects the runner to treat each entry in the baseCommand array as a quoted string?

[Heredoc](http://www.tldp.org/LDP/abs/html/here-docs.html) might be a good idea here, to save you the trouble of escaping symbols.

**Comment by StarvingMarvin** [comment]
@buchanae unfortunately, it's a bit more complicated, because individual command line parts can be unquoted. It also turns out that there are several issues with the way bunny implemented quoting: it defaulted to false (no quoting), even though by the spec default is true. The way it reused escaping code between input parameters and arguments was a bit clunky, and finally, it didn't quote much, even when occasionally it did decided that it should.

Generally the way this should be handled is by not using shell, if possible and instead doing things through passing array of parameters to `Runtime.exec()` which voids any need for quoting. But as I said, because of the need to not quite/escape some parameters, this code needed to be fixed anyway. Current state of the affairs is that on [fix/shell-escaping](https://github.com/rabix/bunny/tree/fix/shell-escaping) branch hello.cwl works, but [this conformance test](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/stagefile.cwl) that used to work, now fails.

**Comment by buchanae** [comment]
Ah, makes sense. Thanks for the explanation.

So, if I understand correctly, the spec expects the engine to determine whether to wrap the part in quotes based on the existence of some characters, such as a whitespace?

**Comment by StarvingMarvin** [comment]
There is an option in [CommandLineBinding](http://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineBinding) to ask engine NOT to quote something. Otherwise it is assumed it will be quoted/escaped, or not being run through shell but invoked directly, which eliminates all shell related issues.

In a meantime, my branch actually [passed the build](https://travis-ci.org/rabix/bunny/builds/206719011) on a build server (including conformance tests) even though it fails locally, so I made a pull request to develop.
