### ISSUE TITLE
bunny vs python version of rabix

### ISSUE THREAD

**Issue by alartin** [rabix/bunny#21]
Hi,
Just confused by bunny project. My understranding rabix is implemented in python for CWL specification. Why there is a bunny of java version under rabix? What's the value of bunny while there is already a more matured python version. It looks to me that python version should be continued and now almost dead. Will python version be deprecated and replaced by bunny?

**Comment by ntijanic** [comment]
Hi,

> Will python version be deprecated and replaced by bunny?

Yes. The CWL specification is still going through iterations, and we wanted to have the ability to run all versions of CWL and combine different versions in a single workflow (which is what bunny can do). 

We chose Java partly because the reference implementation is in Python and it would benefit the CWL community to have implementations in multiple languages.
